### ISSUE TITLE
Ordering the parts

### ISSUE THREAD

**Issue by mantelt** [mantelt/SMB_Assembly-Manual#6]
In [Ordering the parts](https://github.com/turcantuna/SMB_Assembly-Manual/wiki/Ordering-All-The-Parts), maybe mention that this is mostly information for people affiliated with the ETH RobotX Center / ASL&RSL.

**Comment by mantelt** [comment]
Or even better, try to split up the general information from the ETH / RobotX specific information.

**Comment by turcantuna** [comment]
Corrected
