### ISSUE TITLE
Technical drawings

### ISSUE THREAD

**Issue by mantelt** [mantelt/SMB_Assembly-Manual#8]
I would prefer if the technical drawing would show the final state of a part. An otherwise state what the specific technical drawing is used for (e.g. "extra screw holes to adapt old part to new version"). 

For most drawings:
- [x] correct labeling of threaded holes (insipiration: [here](https://s3-eu-west-1.amazonaws.com/3dhubs-knowledgebase/cnc-technical-drawing/Liquid+mixer_v2+Drawing+v21.pdf))

[Camera System AL plate](https://github.com/turcantuna/SMB_Assembly-Manual/blob/master/Descriptions/CameraSystemAl_Plate.PDF):
- [x] The sunk holes to fix the cameras should be in the drawing, not just a note.

**Comment by turcantuna** [comment]
> correct labeling of threaded holes 

I will update the drawings. 

> The sunk holes to fix the cameras should be in the drawing, not just a note.

This was part of the discussion last week, there is an extra drawing that illustrates the chamfer (sunk holes). To make it more clear, I added the link to the [table](https://github.com/turcantuna/SMB_Assembly-Manual/wiki/Aluminium-Plates)

**Comment by turcantuna** [comment]
All the drawings are updated.
